namespace CodeACar.Models
{
    public class User
    {
        /// <summary>
        /// Id of the User entity (Auto generated by the system)
        /// </summary>
        public int Id { get; set; }
        public string Username { get; set; }
        public string PasswordHash { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
    }
}
